Project/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using DataControl;
using Project.Models;
using Project.Data;

namespace Project.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
			if(HomeController.HasCookie(this)){
				DataControl.Repository<Data.User> usr = new DataControl.Repository<Data.User>();
				Service.LogIn(HomeController.GetCookieResult(this));
				if(Service.CurrentUser.IsAdmin){
					return View(Service.CurrentUser);
				}
			}
			return RedirectToAction("Index","Home");
        }
/*@foreach(var usr in @Model.Items){
    <div id="@usr.ID">
        @Html.Partial("UserProfile",usr)
    </div>
} */
		public ActionResult AllUsers(int pg=1) {
			DataControl.Repository<Data.User> rep = new DataControl.Repository<Data.User>();
			int myid = HomeController.GetCookieResult(this);
			//Project.Controllers.Pager<Data.User> pager=new Pager<Data.User>(rep.CurrentSet.Where(x => x.ID != myid));

			return View(rep.CurrentSet.Where(x => x.ID != myid).ToList());
		}

		public ActionResult CreateUser(){
			int id = HomeController.GetCookieResult(this);
			Repository<Data.User> rep = new Repository<Data.User>();

			var usr = rep.GetById(id);
			if(usr==null){
				return RedirectToAction("Index", "Home");
			}else if(!usr.IsAdmin){
				return RedirectToAction("Index", "Home");
			}

			return View("AdminSingIn");
		}

		public ActionResult AdminEdit(int id){
			Data.User nusr = new Data.User();
			nusr.ID = id;

			return View();
		}

		public ActionResult DeleteUser(int id){
			Service.RemoveUser(id);
			return RedirectToAction("AllUsers");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult AdminEdit(Data.User usr) {
			if (!ModelState.IsValid) {
				return View(usr);
			}

			Service.EditUser(usr.ID,usr);
			return RedirectToAction("Index");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult CreateUser(Data.User usr){
			if(!ModelState.IsValid){
				return View(usr);
			}

			Service.AddUser(usr);
			return RedirectToAction("AllUsers");
		}

    }
}

Project/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using DataControl;

namespace Project.Controllers
{
    public class AppointmentController : Controller
    {
        public ActionResult Index(int page=1)
        {
			List<Models.SmartAppointment> smart = new List<Models.SmartAppointment>();
			Repository<Data.Appointment> rep = new Repository<Data.Appointment>();

			if(!HomeController.HasCookie(this)){
				return RedirectToAction("Index", "Home", null);	
			}else if(!Service.LogIn(HomeController.GetCookieResult(this))){
				return RedirectToAction("Index", "Home", null);
			}else if(!Service.Verified(HomeController.GetCookieResult(this))){
				return RedirectToAction("Index", "Home", null);
			}

			foreach (var item in Service.Appointments) {
				if (Service.GetActivity(item.ID).Count() == 0) {
					smart.Add(new Models.SmartAppointment(item, new List<Data.Activity>()));
					continue;
				}

				smart.Add(new Models.SmartAppointment(item,Service.GetActivity(item.ID)));
			}
			
			//Project.Controllers.Pager<Models.SmartAppointment> pager=new Project.Controllers.Pager<Models.SmartAppointment>(
			//	smart.AsQueryable<Models.SmartAppointment>()
			//);
			

			return View (smart);
        }

		public ActionResult CreateAppointment(){
			Models.FullAppointment flpl = new Models.FullAppointment();

			foreach (var item in Service.Activities) {
				flpl.selected.activity.Add(item);
				flpl.selected.selected.Add(false);
			}

			return View(flpl);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult CreateAppointment(Models.FullAppointment smpl) {
			Data.Appointment ap = new Data.Appointment();
			Repository<Data.Appointment> app = new Repository<Data.Appointment>();

			if(!ModelState.IsValid){
				smpl = new Models.FullAppointment();
				foreach (var item in Service.Activities) {
					smpl.selected.activity.Add(item);
					smpl.selected.selected.Add(false);
				}
				return View(smpl);
			}

			ap.UserId = HomeController.GetCookieResult(this);

			var temp = new DateTime();
			if(DateTime.TryParse(smpl.pair.Start,out temp) && DateTime.TryParse(smpl.pair.End,out temp)){
				ap.Start = DateTime.Parse(smpl.pair.Start);
				ap.End = DateTime.Parse(smpl.pair.End);
			}else{
				return RedirectToAction("Index");
			}
			

			Service.AddAppointment(ap);
			int id = app.GetId(ap);

			for (int i = 0; i < smpl.selected.selected.Count;i++) {
				if(smpl.selected.selected[i]){
					Service.PairAppointmentActivity(id,Service.Activities[i].ID);
				}
			}

			return RedirectToAction("Index");
		}

		public ActionResult Edit(int id) {

			return View(new Models.ReplaceAppointment(id,Service.Activities));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(Models.ReplaceAppointment ap){
			List<Data.Activity> res = new List<Data.Activity>();
			var smpl = new Models.ReplaceAppointment();
			if(!ModelState.IsValid){
				foreach (var item in Service.Activities) {
					smpl.selected.activity.Add(item);
					smpl.selected.selected.Add(false);
				}
				return View(smpl);
			}

			for (int i = 0; i < ap.selected.selected.Count(); i++) {
				if(ap.selected.selected[i]){
					res.Add(ap.selected.activity[i]);
				}
			}

			var temp = new DateTime();
			if (!DateTime.TryParse(ap.pair.Start, out temp) || !DateTime.TryParse(ap.pair.End, out temp)) {
				return RedirectToAction("Index");
			}

			Service.UpdateAppointment(
				ap.OldId,
				new Data.Appointment() {
					UserId = HomeController.GetCookieResult(this),
					Start = DateTime.Parse(ap.pair.Start),
					End = DateTime.Parse(ap.pair.End)
				},res);
			return RedirectToAction("Index");
		}

		public ActionResult Delete(int id) {
			Service.RemoveAppointment(id);
			return RedirectToAction("Index");
		}
    }
}

Project/Views/Admin/AdminEdit.cshtml
@model Project.Data.User
@using(Html.BeginForm("AdminEdit","Admin",FormMethod.Post)){
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "warning-message" })

    @Html.HiddenFor(m=>m.ID)
    
    <label>Name: @Html.TextBoxFor(m=>m.Name)</label>
    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "warning-message" })
    <br>

    <label>Password: @Html.PasswordFor(m=>m.Password)</label>
    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "warning-message" })
    <br>

    <label>Email: @Html.TextBoxFor(m=>m.Email)</label>
    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "warning-message" })
    <br>

    <label>Phone: @Html.TextBoxFor(m=>m.Phone)</label>
    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "warning-message" })
    <br>

    <label>Is Admin:@Html.CheckBoxFor(model=>model.IsAdmin)</label>
    <br>

    <input type="submit" />
}

Project/Views/Admin/AdminSingIn.cshtml
@model Project.Data.User
@using(Html.BeginForm("CreateUser","Admin",FormMethod.Post)){
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "warning-message" })

    <label>Name: @Html.TextBoxFor(m=>m.Name)</label>
    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "warning-message" })
    <br>

    <label>Password: @Html.PasswordFor(m=>m.Password)</label>
    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "warning-message" })
    <br>

    <label>Email: @Html.TextBoxFor(m=>m.Email)</label>
    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "warning-message" })
    <br>

    <label>Phone: @Html.TextBoxFor(m=>m.Phone)</label>
    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "warning-message" })
    <br>

    <label>Is Admin:@Html.CheckBoxFor(model=>model.IsAdmin)</label>
    <br>

    <input type="submit" />
}

Project/Views/Admin/AllUsers.cshtml
@model System.Collections.Generic.List<Project.Data.User>
<script src="/Scripts/script.js"></script>
<script>
    var dataBank=@Html.Raw(Json.Encode(Model));
    var table_spec={
        paging: true,
        searching: true,
        stateSave:true,
        "pagingType": "simple",
        "lengthMenu": [[2,5,10, 25, 50, -1], [2,5,10, 25, 50, "All"]],
        "pageLength": 5,
        data:dataBank,
        "columnDefs": [{
            "targets": 5,
            "visible": true,
            "data":null,
            "defaultContent":'@Html.ActionLink("Delete","DeleteUser","Home",null,new {@class="btn delete-button"})'
        },{
            "targets": 0,
            "visible": false,
            data:"ID"
        }],
        columns:[
            {data:"ID"},
            {data:"Name",title:"Name"},
            {data:"Email",title:"Email"},
            {data:"Phone",title:"Phone Number"},
            {data:"IsAdmin",title:"Is Admin"}
        ]
    }
    var table={}

    function displayData(){    
        table=$("#table").DataTable(table_spec);
        Init()
        $('#table tbody').on( 'click', '.btn', function () {
            var data = table.row( $(this).parents('tr') ).data();
            this.href=(this.href+"?id="+data["ID"]);
        });
    }

    window.onload=displayData;
</script>


<div>
    <h2>Other Users:</h2>@Html.ActionLink("Create","CreateUser","Admin",null,new{@class="btn create-button user-option btn"})
</div>

<table id="table" border="3px">

</table>

Project/Views/Admin/Index.cshtml
@model Project.Data.User


@Html.Partial("Profile",@Model)

@Html.ActionLink("View Users","AllUsers","Admin",null,new{@class="btn display-button user-option"});

Project/Views/Admin/Profile.cshtml
@model Project.Data.User

<div class="user-info">

    <h4>ID:@Model.ID</h4>
    <h4>User:@Model.Name</h4>
    <h4>Email:@Model.Email</h4>
    <h4>Phone:@Model.Phone</h4>
    <h4>Is Admin:@Model.IsAdmin.ToString()</h4>
</div>

@Html.ActionLink("Edit","AdminEdit","Admin",new{id=@Model.ID},new{@class="edit-button btn"})
@Html.ActionLink("Delete","DeleteUser","Home",new{id=@Model.ID},new{@class="delete-button btn"})
@Html.ActionLink("Appointments","Index","Appointment",null,new{@class="display-button btn"})
@Html.ActionLink("Activities","Index","Activity",null,new{@class="display-button user-option btn"})

Project/Views/Admin/UserProfile.cshtml
@model Project.Data.User

<div class="user-info">
    <h4>ID:@Model.ID</h4>
    <h4>User:@Model.Name</h4>
    <h4>Email:@Model.Email</h4>
    <h4>Phone:@Model.Phone</h4>
    <h4>Is Admin:@Model.IsAdmin.ToString()</h4>
</div>

@Html.ActionLink("Edit","AdminEdit","Admin",new{id=@Model.ID},new{@class="edit-button btn"})
@Html.ActionLink("Delete","DeleteUser","Home",new{id=@Model.ID},new{@class="delete-button btn"})